# ELASTICSEARCH CONFIDENTIAL
# __________________
#
#  Copyright Elasticsearch B.V. All rights reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Elasticsearch B.V. and its suppliers, if any.
# The intellectual and technical concepts contained herein
# are proprietary to Elasticsearch B.V. and its suppliers and
# may be covered by U.S. and Foreign Patents, patents in
# process, and are protected by trade secret or copyright
# law.  Dissemination of this information or reproduction of
# this material is strictly forbidden unless prior written
# permission is obtained from Elasticsearch B.V.

variable "project" {
  description = "The name of the Google Cloud Platform project in which to create the resources."
  type        = string
}

variable "region" {
  description = "The Google Cloud Platform region in which to create the resources."
  type        = string
}

variable "elastic_api_key" {
  description = "Elastic API key for exporting logs via the Elastic Cloud Forwarder."
  type        = string
  sensitive   = true
}

variable "image" {
  description = "The collector image."
  type        = string
  # TODO: set default to the actual image when this is ready
  # default     = "docker.elastic.co/..."
}

variable "ecf_asset_prefix" {
  description = "Prefix for the ECF assets' names."
  type        = string
  # TODO: set default to an autogenerated prefix when this is mature
  # or maybe not make this a variable at all
}

variable "force_ecf_artifact_registry" {
  description = "Force the use of the Artifact Registry managed by this module for the ECF image."
  type        = bool
  default     = false
}

variable "logs_source_bucket_name" {
  description = "The name of the GCS logs source bucket. If not provided, a new one will be created."
  type        = string
  default     = ""
}

variable "max_instance_request_concurrency" {
  description = "How many concurrent requests the ECF collector can receive."
  type        = number
  default     = 80
}

variable "max_ecf_instance_count" {
  description = "Maximum number of ECF serving instances."
  type        = number
  default     = 100
}

variable "ecf_exporter_endpoint" {
  description = "ECF exporter endpoint."
  type        = string
  default     = ""
}

variable "dead_letter_to_gcs_interval" {
  description = "The maximum interval for flushing a failed message from the dead letter topic to GCS, in seconds."
  type        = number
  default     = 60

  validation {
    error_message = "Maximum duration must be between 60 and 600 seconds."
    condition     = var.dead_letter_to_gcs_interval >= 60 && var.dead_letter_to_gcs_interval <= 600
  }
}

########################################################
# Logging and Internal Telemetry
########################################################

variable "enable_cloud_observability_logging" {
  description = "Enable Cloud Run logging to GCP Logs Explorer. When enabled, grants the Cloud Run service account the 'roles/logging.logWriter' role. Note: This increases costs. Disabled by default."
  type        = bool
  default     = false
}

variable "enable_telemetry" {
  description = "Whether to enable internal telemetry."
  type        = bool
  default     = false
}

variable "telemetry_endpoint" {
  description = "Endpoint to send the internal telemetry to."
  type        = string
  default     = ""
}

variable "es_mapping_mode" {
  description = "Mapping mode to use on the otlphttp exporter. Only used if telemetry endpoint is for elasticsearch."
  type        = string
  default     = "otel"
}

variable "include_metadata" {
  description = "Whether to add extra metadata to the logs (bucket, object, subscription, message ID, delivery attempt)."
  type        = bool
  default     = false
}


variable "telemetry_additional_attributes" {
  description = "Additional attributes to add to the internal telemetry."
  type        = map(string)
  default     = {}
}

variable "telemetry_api_key" {
  description = "API key for the telemetry endpoint."
  type        = string
  sensitive   = true
  default     = ""
}

#######################################################
# Cloud Run Resource Limits
#######################################################

variable "ecf_container_memory" {
  description = "ECF Cloud Run container memory. Check https://cloud.google.com/run/docs/configuring/services/memory-limits#cpu-minimum."
  type        = string
  default     = "512Mi"
}

variable "ecf_container_cpu" {
  description = "ECF Cloud Run container CPU."
  type        = string
  default     = "1"
}

#######################################################
# Pub/Sub Retry Policy
#######################################################

variable "retry_minimum_backoff" {
  description = "The minimum delay between consecutive deliveries of a given message to ECF collector, in seconds."
  type        = number
  default     = 10

  validation {
    error_message = "Retry minimum backoff must have a value between 0 and 600."
    condition     = var.retry_minimum_backoff >= 0 && var.retry_minimum_backoff <= 600
  }
}

variable "retry_maximum_backoff" {
  description = "The maximum delay between consecutive deliveries of a given message to ECF collector, in seconds."
  type        = number
  default     = 60

  validation {
    error_message = "Retry maximum backoff must have a value between 0 and 600, and equal or higher than retry_minimum_backoff."
    condition     = var.retry_maximum_backoff >= 0 && var.retry_maximum_backoff <= 600 && var.retry_maximum_backoff >= var.retry_minimum_backoff
  }
}

variable "retry_maximum_attempts" {
  description = "The maximum attempts to deliver a given message to ECF collector."
  type        = number
  default     = 5

  validation {
    error_message = "Retry maximum attempts must have a value between 5 and 100."
    condition     = var.retry_maximum_attempts >= 5 && var.retry_maximum_attempts <= 100
  }
}
