# ELASTICSEARCH CONFIDENTIAL
# __________________
#
#  Copyright Elasticsearch B.V. All rights reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Elasticsearch B.V. and its suppliers, if any.
# The intellectual and technical concepts contained herein
# are proprietary to Elasticsearch B.V. and its suppliers and
# may be covered by U.S. and Foreign Patents, patents in
# process, and are protected by trade secret or copyright
# law.  Dissemination of this information or reproduction of
# this material is strictly forbidden unless prior written
# permission is obtained from Elasticsearch B.V.

variable "project" {
  description = "The name of the Google Cloud Platform project in which to create the resources."
  type        = string
}

variable "region" {
  description = "The Google Cloud Platform region in which to create the resources."
  type        = string
}

variable "elastic_api_key" {
  description = "Elastic API key for exporting logs via the Elastic Cloud Forwarder."
  type        = string
  sensitive   = true
}

variable "image_name" {
  description = "The collector image name."
  type        = string
  default     = "edot-cloud-forwarder"
}

variable "registry_name" {
  description = "Name of the artifact registry where the collector container is."
  type        = string
  # TODO: set default to the actual registry name when this is mature
  # or maybe not make this a variable at all
}

variable "ecf_asset_prefix" {
  description = "Prefix for the ECF assets' names."
  type        = string
  # TODO: set default to an autogenerated prefix when this is mature
  # or maybe not make this a variable at all
}