# ELASTICSEARCH CONFIDENTIAL
# __________________
#
#  Copyright Elasticsearch B.V. All rights reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Elasticsearch B.V. and its suppliers, if any.
# The intellectual and technical concepts contained herein
# are proprietary to Elasticsearch B.V. and its suppliers and
# may be covered by U.S. and Foreign Patents, patents in
# process, and are protected by trade secret or copyright
# law.  Dissemination of this information or reproduction of
# this material is strictly forbidden unless prior written
# permission is obtained from Elasticsearch B.V.

# The directory that stores individual changelog entries.
entries_dir: .chloggen

# This file is used as the input for individual changelog entries.
template_yaml: .chloggen/TEMPLATE.yaml

# Template file for the generated changelog.
summary_template: .chloggen/summary.tmpl

# The CHANGELOG file or files to which 'chloggen update' will write new entries
change_logs:
  all: CHANGELOG.md

# The default change_log or change_logs to which an entry should be added.
default_change_logs:
  - all