# ELASTICSEARCH CONFIDENTIAL
# __________________
#
#  Copyright Elasticsearch B.V. All rights reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Elasticsearch B.V. and its suppliers, if any.
# The intellectual and technical concepts contained herein
# are proprietary to Elasticsearch B.V. and its suppliers and
# may be covered by U.S. and Foreign Patents, patents in
# process, and are protected by trade secret or copyright
# law.  Dissemination of this information or reproduction of
# this material is strictly forbidden unless prior written
# permission is obtained from Elasticsearch B.V.

name: changelog-md-edit

on:
  pull_request:
    branches:
      - main

jobs:
  changelog-md-edit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.actor != 'elastic-observability-automation'}}
    env:
      PR_HEAD: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0 # we need the commit history

      - name: Ensure no changes to the CHANGELOG.md file
        run: |
          if [[ $(git diff --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./CHANGELOG.md) ]]
          then
            echo "::error::CHANGELOG.md file is autogenerated and cannot be updated."
            echo "::error::Please remove CHANGELOG.md from your PR and add a changelog fragment by running 'make chlog-new'."
            exit 1
          fi